/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutAboutRouteImport } from './routes/_layout/about'
import { Route as LayoutTemplatesIndexRouteImport } from './routes/_layout/templates/index'
import { Route as LayoutTemplatesSlugRouteImport } from './routes/_layout/templates/$slug'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutAboutRoute = LayoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTemplatesIndexRoute = LayoutTemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTemplatesSlugRoute = LayoutTemplatesSlugRouteImport.update({
  id: '/templates/$slug',
  path: '/templates/$slug',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof LayoutAboutRoute
  '/templates/$slug': typeof LayoutTemplatesSlugRoute
  '/templates/': typeof LayoutTemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof LayoutAboutRoute
  '/templates/$slug': typeof LayoutTemplatesSlugRoute
  '/templates': typeof LayoutTemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/about': typeof LayoutAboutRoute
  '/_layout/templates/$slug': typeof LayoutTemplatesSlugRoute
  '/_layout/templates/': typeof LayoutTemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/templates/$slug' | '/templates/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/templates/$slug' | '/templates'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/_layout/about'
    | '/_layout/templates/$slug'
    | '/_layout/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/about': {
      id: '/_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutAboutRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/templates/': {
      id: '/_layout/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof LayoutTemplatesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/templates/$slug': {
      id: '/_layout/templates/$slug'
      path: '/templates/$slug'
      fullPath: '/templates/$slug'
      preLoaderRoute: typeof LayoutTemplatesSlugRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAboutRoute: typeof LayoutAboutRoute
  LayoutTemplatesSlugRoute: typeof LayoutTemplatesSlugRoute
  LayoutTemplatesIndexRoute: typeof LayoutTemplatesIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAboutRoute: LayoutAboutRoute,
  LayoutTemplatesSlugRoute: LayoutTemplatesSlugRoute,
  LayoutTemplatesIndexRoute: LayoutTemplatesIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.ts'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
